export default [
  {
    Topic:
      'Compilation error  building on iOS simulator:fatal error: could not build module',
    Type: 'Problem',
    name: 'Mavine Naaman',
    count: 6,
    status: 'open',
    comments: 'comments',
    id: 1,
  },
  {
    Topic: 'Testing the text',
    Type: 'Foundation',
    name: 'Mavine Naaman',
    count: 20,
    status: 'open',
    comments: 'comments',
    id: 2,
  },
  {
    Topic: 'Testing the text',
    Type: 'Problem',
    name: 'Developer',
    count: 10,
    status: 'open',
    comments: 'comments',
    id: 3,
  },
  {
    Topic: 'Can You react natively',
    Type: 'Problem',
    name: 'React Native',
    count: 15,
    status: 'open',
    comments: 'comments',
    id: 4,
  },
  {
    Topic: 'Testing the text',
    Type: 'Foundation',
    name: 'Ken Kings',
    count: 10,
    status: 'open',
    comments: 'comments',
    id: 5,
  },
  {
    Topic: '',
    Type: 'Empty',
    status: 'closed',
    name: 'Tester',
    comments: 'comments',
    id: 6,
  },
  {
    Topic: '',
    Type: 'Empty',
    name: 'Mavine Naaman',
    count: 60,
    status: 'closed',
    comments: 'comments',
    id: 7,
  },
];
